spring.application.name=Td5_spring
spring.datasource.url=jdbc:postgresql://localhost:5432/product_management_db
spring.datasource.username=product_manager_user
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never